#! /bin/sh
#
# This script downloads and builds an API tester. This script was copied to
# Gist from Samba. Original license applies.

set -e

rm -f preload_fileops.c
wget --no-check-certificate https://raw.github.com/gist/1491092/e97d5b415d7399e75ed1a05a041cef669d5bad17/preload_fileops.c
gcc -fPIC -c preload_fileops.c -o preload_fileops.o
gcc -shared -o preload_fileops.so preload_fileops.o -ldl
